grails-app/views/email/_unsubscribe.gsp
grails-app/views/email/alert.gsp
grails-app/views/email/biocache.gsp
grails-app/views/email/biocacheImages.gsp
grails-app/views/email/datasets.gsp
grails-app/views/email/layers.gsp

change linked text in emails from 'click here' to descriptive / unique text per link.

change link text for better accessibility

---

grails-app/controllers/au/org/ala/alerts/NotificationController.groovy
grails-app/controllers/au/org/ala/alerts/UnsubscribeController.groovy
grails-app/controllers/au/org/ala/alerts/WebserviceController.groovy
grails-app/init/au/org/ala/alerts/BootStrap.groovy
grails-app/services/au/org/ala/alerts/NotificationService.groovy
grails-app/views/notification/myAlerts.gsp
src/test/groovy/au/org/ala/alerts/UnsubscribeControllerSpec.groovy

renaming 'my annotation' related APIs
for issue https://github.com/AtlasOfLivingAustralia/alerts/issues/110

changed add/delete myannotaion to subscribe/unsubscribe myannotaion.

---

grails-app/i18n/messages.properties
grails-app/services/au/org/ala/alerts/EmailService.groovy
grails-app/services/au/org/ala/alerts/WebService.groovy
grails-app/views/email/biosecurity.gsp

for https://github.com/AtlasOfLivingAustralia/alerts/issues/133

added species list name, link to biosecurity email

---

grails-app/i18n/messages.properties
grails-app/services/au/org/ala/alerts/EmailService.groovy
grails-app/services/au/org/ala/alerts/NotificationService.groovy
grails-app/services/au/org/ala/alerts/QueryService.groovy
grails-app/views/email/biosecurity.gsp

to include **biosecurity user annotation** in alert email, like below
<br><br><br>

retrieve biosecurity user assertions and put them in alert email

---

grails-app/i18n/messages.properties
grails-app/services/au/org/ala/alerts/EmailService.groovy
grails-app/services/au/org/ala/alerts/QueryService.groovy
grails-app/services/au/org/ala/alerts/UserService.groovy
grails-app/views/admin/biosecurity.gsp
grails-app/views/email/biosecurity.gsp

#141 - Also cleaned-up UI and added a few more fields. User assertions now showing.

#141 Add static map to biosecurity email

---

grails-app/views/admin/index.gsp

Re-structuring Admin UI and adding descriptive comments to admin functions

issue #171 updating  admin ui and adding descriptions

---

build.gradle
grails-app/init/au/org/ala/alerts/BootStrap.groovy
grails-app/services/au/org/ala/alerts/NotificationService.groovy
grails-app/views/admin/index.gsp

Minor bugfixes and admin UI improvement

Merge develop to master for 2.0.2 release

---

build.gradle
grails-app/services/au/org/ala/alerts/UserService.groovy

Addresses point 2 and 3 of issue #174

Batch up user update calls to UserDetails webservices (#174)

---

build.gradle
grails-app/services/au/org/ala/alerts/NotificationService.groovy
grails-app/views/email/blogs.gsp
grails-app/views/layouts/main.gsp

237 blog alerts coming through instead of in blog description preview text

---

grails-app/services/au/org/ala/alerts/BiosecurityService.groovy

#275 Fix for `no transaction is in progress` exception for biosecurity alerts

---

grails-app/views/email/blogs.gsp

#237 Minor HTML tweaks for blogs.gsp

---

grails-app/views/email/biosecurity.gsp
grails-app/views/email/blogs.gsp

#280 email rendering issues

---

grails-app/controllers/au/org/ala/alerts/NotificationController.groovy
grails-app/services/au/org/ala/alerts/NotificationService.groovy

Just version number is different.

Syncing develop with master

---

build.gradle

Version 4.2.3

---

build.gradle

Merge `release/4.2.4` into `develop`

Bump version to 4.2.4

---

.travis.yml
build.gradle
grails-app/assets/stylesheets/alerts.css
grails-app/controllers/au/org/ala/alerts/AdminController.groovy
grails-app/services/au/org/ala/alerts/BiosecurityCSVService.groovy
grails-app/views/admin/_bioSecuritySubscription.gsp

#298 Fix for CSV files not escaping internal commons

---

build.gradle
grails-app/conf/application.yml
grails-app/services/au/org/ala/alerts/AlertsWebService.groovy
grails-app/services/au/org/ala/alerts/BiosecurityService.groovy
grails-app/services/au/org/ala/alerts/NotificationService.groovy

#291 and additional change for #261 included.

291 add useragent for alerts

---

grails-app/i18n/messages.properties
grails-app/views/notification/myAlerts.gsp

#45 Show user locked status on alerts page

---

cicd/base/app/base.yaml

create instance profile

---

cicd/database/app/database.yaml
cicd/database/app/database_template_config.j2
cicd/database/config.ini

* make enhanced monitoring configurable
* disable performance insights in testing
* dont create a read replica in testing
* dont specify role if there's no Enhanced Monitoring

Feature/scale 2 zero (#348)

---

grails-app/controllers/au/org/ala/alerts/AdminController.groovy
grails-app/domain/au/org/ala/alerts/Query.groovy
grails-app/services/au/org/ala/alerts/BiosecurityService.groovy
grails-app/services/au/org/ala/alerts/NotificationService.groovy

And the preview data was unexpectedly stored in the database.

#357 fix lastcheck date in Biosecurity alerts for the scheduler

---

build.gradle
grails-app/services/au/org/ala/alerts/NotificationService.groovy

#386 catch a possible exception from userService

---

cicd/backend/config.ini
cicd/backend/pipeline/export_config_buildspec.yaml
helm/config/alerts-config.properties
helm/values.yaml

* Add email enable variable to config
* Update skinicon prod

Add email enable variable to config (#429)

---

helm/templates/ingress.yaml

* Increase ALB connection idle timeout to 90s
* Fixed attribute name

Increase ALB connection idle timeout to 90s (#433)

---

cicd/backend/pipeline/build_alerts_buildspec.yaml
cicd/backend/pipeline/export_config_buildspec.yaml
cicd/backend/pipeline/pipeline.yaml
cicd/base/app/base.yaml
cicd/base/pipeline/empty_bucket_buildspec.yaml
cicd/base/pipeline/pipeline.yaml
helm/templates/ingress.yaml
helm/values.yaml

* [CICD] Enable access logs
* Add ownership controls in CF
* Cleanup

[CICD] Enable access logs (#447)

---

build.gradle
cicd/backend/pipeline/build_alerts_buildspec.yaml
cicd/backend/pipeline/deploy_alerts_buildspec.yaml
cicd/backend/pipeline/deploy_pipeline.sh
cicd/backend/pipeline/export_config_buildspec.yaml
cicd/backend/pipeline/pipeline.yaml
cicd/base/app/base.yaml
cicd/base/pipeline/empty_bucket_buildspec.yaml
cicd/base/pipeline/pipeline.yaml
grails-app/services/au/org/ala/alerts/NotificationService.groovy
helm/Chart.yaml
helm/templates/ingress.yaml
helm/values.yaml

Release notes:
- Fix for bug in unsubscribe link alerts emails [#444 ](https://github.com/AtlasOfLivingAustralia/alerts/issues/444)
- Enable load balancer access logs in AWS, pushed to S3
- Codepipeline enhancements

Release 5.0.6

---

grails-app/conf/application.yml
grails-app/services/au/org/ala/alerts/NotificationService.groovy

Biocache or Nginx does not support [&]

#454 Encode [ and ] in query params
